components:
  securitySchemes:
    ldapCredentials:
      scheme: basic
      type: http
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        type: integer
  parameters:
    ipa_code:
      description: Il codice IPA dell'amministrazione.
      example: asl_lt
      in: path
      name: ipa_code
      required: true
      schema:
        type: string
    limit:
      description: How many items to return at one time (max 100)
      in: query
      name: limit
      schema:
        format: int32
        type: integer
    name:
      description: La stringa da ricercare nel nome dell'amministrazione.
      example: Latina
      in: query
      name: name
      required: true
      schema:
        type: string
    offset:
      description: The zero-ary offset index into the results
      in: query
      name: offset
      schema:
        default: 0
        format: int32
        type: integer
    sort:
      description: Sorting order
      in: query
      name: sort
      schema:
        example: +name
        type: string
  responses:
    400BadRequest:
      content:
        application/problem+json:
          schema:
            properties:
              detail:
                description: |
                  A human readable explanation specific to this occurrence of the
                  problem.
                example: Connection to database timed out
                type: string
              instance:
                description: |
                  An absolute URI that identifies the specific occurrence of the problem.
                  It may or may not yield further information if dereferenced.
                format: uri
                type: string
              status:
                description: |
                  The HTTP status code generated by the origin server for this occurrence
                  of the problem.
                example: 503
                exclusiveMaximum: true
                format: int32
                maximum: 600
                minimum: 100
                type: integer
              title:
                description: |
                  A short, summary of the problem type. Written in english and readable
                  for engineers (usually not suited for non technical stakeholders and
                  not localized); example: Service Unavailable
                type: string
              type:
                default: about:blank
                description: |
                  An absolute URI that identifies the problem type.  When dereferenced,
                  it SHOULD provide human-readable documentation for the problem type
                  (e.g., using HTML).
                example: https://tools.ietf.org/html/rfc7231#section-6.6.4
                format: uri
                type: string
            type: object
      description: Bad Request
    404NotFound:
      content:
        application/problem+json:
          schema:
            properties:
              detail:
                description: |
                  A human readable explanation specific to this occurrence of the
                  problem.
                example: Connection to database timed out
                type: string
              instance:
                description: |
                  An absolute URI that identifies the specific occurrence of the problem.
                  It may or may not yield further information if dereferenced.
                format: uri
                type: string
              status:
                description: |
                  The HTTP status code generated by the origin server for this occurrence
                  of the problem.
                example: 503
                exclusiveMaximum: true
                format: int32
                maximum: 600
                minimum: 100
                type: integer
              title:
                description: |
                  A short, summary of the problem type. Written in english and readable
                  for engineers (usually not suited for non technical stakeholders and
                  not localized); example: Service Unavailable
                type: string
              type:
                default: about:blank
                description: |
                  An absolute URI that identifies the problem type.  When dereferenced,
                  it SHOULD provide human-readable documentation for the problem type
                  (e.g., using HTML).
                example: https://tools.ietf.org/html/rfc7231#section-6.6.4
                format: uri
                type: string
            type: object
      description: Not Found
    429TooManyRequests:
      content:
        application/problem+json:
          schema:
            properties:
              detail:
                description: |
                  A human readable explanation specific to this occurrence of the
                  problem.
                example: Connection to database timed out
                type: string
              instance:
                description: |
                  An absolute URI that identifies the specific occurrence of the problem.
                  It may or may not yield further information if dereferenced.
                format: uri
                type: string
              status:
                description: |
                  The HTTP status code generated by the origin server for this occurrence
                  of the problem.
                example: 503
                exclusiveMaximum: true
                format: int32
                maximum: 600
                minimum: 100
                type: integer
              title:
                description: |
                  A short, summary of the problem type. Written in english and readable
                  for engineers (usually not suited for non technical stakeholders and
                  not localized); example: Service Unavailable
                type: string
              type:
                default: about:blank
                description: |
                  An absolute URI that identifies the problem type.  When dereferenced,
                  it SHOULD provide human-readable documentation for the problem type
                  (e.g., using HTML).
                example: https://tools.ietf.org/html/rfc7231#section-6.6.4
                format: uri
                type: string
            type: object
      description: Too many requests
      headers:
        Retry-After:
          description: |-
            Retry contacting the endpoint *at least* after seconds.
            See https://tools.ietf.org/html/rfc7231#section-7.1.3
          schema:
            format: int32
            type: integer
        X-RateLimit-Limit:
          description: The number of allowed requests in the current period
          schema:
            format: int32
            type: integer
        X-RateLimit-Remaining:
          description: The number of remaining requests in the current period
          schema:
            format: int32
            type: integer
        X-RateLimit-Reset:
          description: The number of seconds left in the current period
          schema:
            format: int32
            type: integer
    503ServiceUnavailable:
      content:
        application/problem+json:
          schema:
            Problem:
              properties:
                detail:
                  description: |
                    A human readable explanation specific to this occurrence of the
                    problem.
                  example: Connection to database timed out
                  type: string
                instance:
                  description: |
                    An absolute URI that identifies the specific occurrence of the problem.
                    It may or may not yield further information if dereferenced.
                  format: uri
                  type: string
                status:
                  description: |
                    The HTTP status code generated by the origin server for this occurrence
                    of the problem.
                  example: 503
                  exclusiveMaximum: true
                  format: int32
                  maximum: 600
                  minimum: 100
                  type: integer
                title:
                  description: |
                    A short, summary of the problem type. Written in english and readable
                    for engineers (usually not suited for non technical stakeholders and
                    not localized); example: Service Unavailable
                  type: string
                type:
                  default: about:blank
                  description: |
                    An absolute URI that identifies the problem type.  When dereferenced,
                    it SHOULD provide human-readable documentation for the problem type
                    (e.g., using HTML).
                  example: https://tools.ietf.org/html/rfc7231#section-6.6.4
                  format: uri
                  type: string
              type: object
      description: Service Unavailable
      headers:
        Retry-After:
          description: |-
            Retry contacting the endpoint *at least* after seconds.
            See https://tools.ietf.org/html/rfc7231#section-7.1.3
          schema:
            format: int32
            type: integer
    default:
      content:
        application/problem+json:
          schema:
            properties:
              detail:
                description: |
                  A human readable explanation specific to this occurrence of the
                  problem.
                example: Connection to database timed out
                type: string
              instance:
                description: |
                  An absolute URI that identifies the specific occurrence of the problem.
                  It may or may not yield further information if dereferenced.
                format: uri
                type: string
              status:
                description: |
                  The HTTP status code generated by the origin server for this occurrence
                  of the problem.
                example: 503
                exclusiveMaximum: true
                format: int32
                maximum: 600
                minimum: 100
                type: integer
              title:
                description: |
                  A short, summary of the problem type. Written in english and readable
                  for engineers (usually not suited for non technical stakeholders and
                  not localized); example: Service Unavailable
                type: string
              type:
                default: about:blank
                description: |
                  An absolute URI that identifies the problem type.  When dereferenced,
                  it SHOULD provide human-readable documentation for the problem type
                  (e.g., using HTML).
                example: https://tools.ietf.org/html/rfc7231#section-6.6.4
                format: uri
                type: string
            type: object
      description: Unexpected error
  schemas:
    PA:
      description: Una Pubblica Amministrazione.
      type: object
    Problem:
      properties:
        detail:
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Connection to database timed out
          type: string
        instance:
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
          format: uri
          type: string
        status:
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          example: 503
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
          type: string
        type:
          default: about:blank
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          example: https://tools.ietf.org/html/rfc7231#section-6.6.4
          format: uri
          type: string
      type: object
info:
  contact:
    email: robipolli@gmail.com
    name: Roberto Polli
    url: https://twitter.com/ioggstream
  description: |
    Questa prima linea verr√† usata come sottotitolo. Descrive brevemente e in linguaggio comune il servizio.
    \
    \
    #### Documentazione
    Qui devi inserire la documentazione principale del servizio. Usa due "\" per separare il sottotitolo dalla documentazione.
    Il testo dev'essere diviso in piu' parti, tutte scritte in Markdown.

    Questa sezione e' informativa:

      * cosa fanno queste API?
      * chi puo' beneficiarne?
      * perche' sono utili?

    ##### Sottosezioni
    E' possibile utilizzare - con criterio - delle sottosezioni.

    #### Note

    Usa questa sezione per annotazioni specifiche, riferimenti normativi e/o
    per manleve ed esclusioni di responsabilita' eventualmente non incluse in `termsOfService`.

    #### Informazioni tecniche ed esempi

    Qui e' possibile introdurre brevi informazioni tecniche ed esempi.
    Attenzione: la `description` non sostituisce la documentazione di progetto,
    deve pero' facilitare l'esecuzione delle prime richieste.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Starter Kit API
  version: 1.0.0
  x-api-id: 71afb493-b5a1-44ed-a997-991c217f520c
  x-audience:
  - public
openapi: 3.0.0
paths:
  /indicepa:
    get:
      description: |
        Si connette ad IndicePA e ricerca una PA per nome.
      operationId: search_ipa
      parameters:
      - $ref: '#/components/parameters/name'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/sort'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PA'
          description: |
            La PA e' stata trovata e le informazioni sono state recuperate
            con successo.
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          description: Credenziali LDAP non valide.
        '404':
          $ref: '#/components/responses/404NotFound'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
        default:
          $ref: '#/components/responses/default'
      security:
      - ldapCredentials: []
      summary: Ricerca una PA per nome.
      tags:
      - public
  /indicepa/{ipa_code}:
    get:
      description: |
        Si connette ad IndicePA e recupera le informazioni su
        un'amministrazione tramite il codice IPA.
      operationId: get_ipa
      parameters:
      - $ref: '#/components/parameters/ipa_code'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PA'
          description: |
            La PA e' stata trovata e le informazioni sono state recuperate
            con successo.
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          description: Credenziali LDAP non valide.
        '404':
          $ref: '#/components/responses/404NotFound'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
        default:
          $ref: '#/components/responses/default'
      security:
      - ldapCredentials: []
      summary: Recupera le informazioni su una PA.
      tags:
      - public
servers:
- description: Test server
  url: https://api.example.com/ipa/v1
- description: Development server
  url: https://localhost:8443/ipa/v1
tags:
- description: Retrieve informations
  externalDocs:
    url: http://docs.my-api.com/pet-operations.htm
  name: public
